# Generated by Django 4.2 on 2024-06-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='request',
            new_name='request_grp',
        ),
    ]
