# Generated by Django 4.2 on 2024-06-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_request_message_request_grp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=60, null=True)),
                ('username', models.CharField(max_length=60, null=True)),
                ('stage', models.BooleanField(null=True)),
                ('notification', models.IntegerField(null=True)),
            ],
        ),
    ]
