# Generated by Django 4.2 on 2024-07-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
